import { describe, expect, it } from "vitest";
import { calculateEndTime, generatePatternMonth, mergeGeneratedWithManual, validateSchedule, worksOnDate, type EnginePattern, type ValidationPerson } from "./escala-engine";
const p=(tipo:EnginePattern["tipo"],data_base:string|null,folgas_fixas:number[]=[])=>({tipo,data_base,folgas_fixas,folga_semana_a:0,folga_semana_b:1});
describe("escala-engine",()=>{
 it("mantém 12x36 em viradas de mês e ano",()=>{const a=p("12x36","2026-10-31");expect(worksOnDate(a,"2026-10-31")).toBe(true);expect(worksOnDate(a,"2026-11-01")).toBe(false);const b=p("12x36","2026-12-31");expect(worksOnDate(b,"2027-01-01")).toBe(false);});
 it("não escala manutenção no fim de semana",()=>{const days=generatePatternMonth(p("5x2_fixo",null,[0,6]),2026,9);expect(days.filter(d=>[0,6].includes(new Date(`${d.data}T00:00:00Z`).getUTCDay())).every(d=>d.status==="folga")).toBe(true);});
 it("reproduz o revezamento de Ipanema",()=>{const x=p("5x2_revezamento","2026-10-04",[3]);const dates=["2026-09-30","2026-10-04","2026-10-05","2026-10-07","2026-10-14","2026-10-18","2026-10-19","2026-10-21","2026-10-28","2026-11-01"];expect(dates.every(d=>!worksOnDate(x,d))).toBe(true);});
 it("detecta sexta+sábado, sábado+domingo e 7 dias",()=>{const pattern=p("5x2_revezamento","2026-10-04",[3]);const days=Array.from({length:10},(_,i)=>({data:`2026-10-${String(i+1).padStart(2,"0")}`,status:"trabalho" as const}));days[1].status="folga";days[2].status="folga";days[8].status="folga";days[9].status="folga";const person:ValidationPerson={id:"1",nome:"Maria",setor:"camareiras",unidade:"Ipanema",turno:"dia",pattern,days};const codes=validateSchedule([person]).map(i=>i.code);expect(codes).toContain("friday_saturday_off");expect(codes).toContain("saturday_sunday_off");expect(validateSchedule([{...person,days:Array.from({length:7},(_,i)=>({data:`2026-10-${String(i+1).padStart(2,"0")}`,status:"trabalho" as const}))}]).map(i=>i.code)).toContain("seven_days");});
 it("preserva manual e calcula saída",()=>{const g=[{colaborador_id:"1",data:"2026-10-01",turno:"dia",origem:"gerado" as const}];const m=[{...g[0],origem:"manual" as const}];expect(mergeGeneratedWithManual(g,m)).toEqual(m);expect(calculateEndTime("20:00",12)).toBe("08:00");});
});
