import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { supabase } from "@/integrations/supabase/client";
import { recalcularPrevisaoCarga } from "@/lib/previsao-carga.functions";

export type ForecastLevel="verde"|"amarelo"|"vermelho";
export type ForecastRow={id:string;unidade:string;data:string;calculado_em:string;qtd_geral:number;qtd_geral_checkin:number;qtd_troca_arrumacao:number;qtd_arrumacao:number;qtd_checkins:number;qtd_checkouts:number;carga_minutos:number;capacidade_minutos:number;camareiras_escaladas:number;freelancers_escalados:number;ocupacao_carga_pct:number;nivel:ForecastLevel;chegada_mais_cedo:string|null;detalhes:unknown;capacidade_detalhes:unknown};
export type ForecastConfig={unidade:string;geral_minutos:number;geral_checkin_minutos:number;troca_arrumacao_minutos:number;arrumacao_minutos:number;margem_pct:number;limite_amarelo_pct:number;limite_vermelho_pct:number;limite_amarelo_gerais:number;limite_vermelho_gerais:number};
export type ForecastMedian={unidade:string;tarefa:string;amostras:number;mediana_minutos:number};
export function usePrevisaoCarga(){return useQuery({queryKey:["previsao-carga"],queryFn:async()=>{const{data,error}=await supabase.from("previsao_carga").select("*").gte("data",new Date().toISOString().slice(0,10)).order("calculado_em",{ascending:false});if(error)throw error;const latest=new Map<string,ForecastRow>();for(const row of data??[]){const key=`${row.unidade}|${row.data}`;if(!latest.has(key))latest.set(key,row as ForecastRow);}return [...latest.values()].sort((a,b)=>a.data.localeCompare(b.data)||a.unidade.localeCompare(b.unidade));}});}
export function usePrevisaoConfig(){return useQuery({queryKey:["previsao-carga-config"],queryFn:async()=>{const{data,error}=await supabase.from("previsao_carga_config").select("*").order("unidade");if(error)throw error;return(data??[]) as ForecastConfig[];}});}
export function usePrevisaoMedianas(){return useQuery({queryKey:["previsao-tempos-medianos"],queryFn:async()=>{const{data,error}=await supabase.from("previsao_tempos_medianos").select("*");if(error)throw error;return(data??[]) as ForecastMedian[];}});}
export function useCalibracaoPrevisao(){return useQuery({queryKey:["previsao-calibracao"],queryFn:async()=>{const end=new Date().toISOString().slice(0,10),start=new Date(Date.now()-31*86400000).toISOString().slice(0,10);const[{data:snapshots,error:snapshotError},{data:history,error:historyError},{data:configs,error:configError}]=await Promise.all([supabase.from("previsao_carga").select("*").eq("horizonte_dias",2).gte("data",start).lte("data",end).order("calculado_em",{ascending:true}),supabase.from("room_housekeeping_history").select("property,task_name,started_at,ended_at").gte("started_at",`${start}T00:00:00Z`),supabase.from("previsao_carga_config").select("*")]);if(snapshotError)throw snapshotError;if(historyError)throw historyError;if(configError)throw configError;const configByUnit=new Map(((configs??[]) as ForecastConfig[]).map(c=>[c.unidade,c]));const daySP=(iso:string|null)=>iso?new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date(iso)):"";const first=new Map<string,ForecastRow>();for(const row of snapshots??[]){const key=`${row.unidade}|${row.data}`;if(!first.has(key))first.set(key,row as ForecastRow);}return [...first.values()].map(row=>{const actual=(history??[]).filter(item=>item.property===row.unidade&&daySP(item.started_at)===row.data);const gerais=actual.filter(item=>String(item.task_name).toUpperCase().startsWith("GERAL")).length;const minutos=Math.round(actual.reduce((sum,item)=>sum+(item.started_at&&item.ended_at?Math.max(0,(new Date(item.ended_at).getTime()-new Date(item.started_at).getTime())/60000):0),0));// "Dia pesado" = o que de fato aconteceu passou do limite vermelho de gerais
// ou o tempo real de limpeza passou da capacidade escalada naquele dia.
const cfg=configByUnit.get(row.unidade);const limiteGerais=cfg?.limite_vermelho_gerais??Number.POSITIVE_INFINITY;const capacidade=Number(row.capacidade_minutos)||0;const heavy=gerais>=limiteGerais||(capacidade>0&&minutos>capacidade);const alerted=row.nivel!=="verde";return{unidade:row.unidade,data:row.data,alerted,heavy,gerais,minutos,result:alerted&&heavy?"acerto":alerted?"alarme_falso":heavy?"nao_detectado":"normal"};});}});}
export function useSalvarPrevisaoConfig(){const qc=useQueryClient();return useMutation({mutationFn:async(row:ForecastConfig)=>{const{error}=await supabase.from("previsao_carga_config").update(row).eq("unidade",row.unidade);if(error)throw error;},onSuccess:()=>qc.invalidateQueries({queryKey:["previsao-carga-config"]})});}
export function useRecalcularPrevisao(){const call=useServerFn(recalcularPrevisaoCarga),qc=useQueryClient();return useMutation({mutationFn:(unidades:("Botafogo"|"Ipanema")[])=>call({data:{unidades}}),onSuccess:()=>qc.invalidateQueries({queryKey:["previsao-carga"]})});}