import { Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowUpRight, CheckCircle2, Gauge } from "lucide-react";
import { Card } from "@/components/ui/card";
import { usePrevisaoCarga } from "@/lib/previsao-carga";
import { usePedidosPendentes } from "@/components/gestao/pedidos-reforco";
import { addCivilDays } from "@/lib/escala-engine";
import { todaySP } from "@/lib/tz";
import { cn } from "@/lib/utils";

const tones={verde:"border-emerald-200 bg-emerald-50 text-emerald-800",amarelo:"border-amber-200 bg-amber-50 text-amber-800",vermelho:"border-red-200 bg-red-50 text-red-800"};
export function PrevisaoCargaCard(){const query=usePrevisaoCarga();const pendentes=usePedidosPendentes();const target=addCivilDays(todaySP(),2);const rows=(query.data??[]).filter(row=>row.data===target);return <section className="space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Gauge className="h-5 w-5 text-amber-600"/><h2 className="text-xs font-black uppercase text-slate-500">Reforço em 2 dias</h2>{pendentes.length>0&&<Link to="/gestor/previsao-carga" className="rounded-full bg-red-600 px-2 py-0.5 text-[11px] font-black text-white">{pendentes.length} pedido(s) da Recepção</Link>}</div><Link to="/gestor/previsao-carga" className="flex items-center gap-1 text-xs font-bold text-blue-700">Abrir previsão<ArrowUpRight className="h-3.5 w-3.5"/></Link></div><div className="grid gap-3 sm:grid-cols-2">{rows.length?rows.map(row=><Card key={row.id} className={cn("p-4",tones[row.nivel])}><div className="flex items-center justify-between"><strong>{row.unidade}</strong><span className="text-xs font-black uppercase">{row.nivel}</span></div><p className="mt-2 text-2xl font-black">{row.qtd_geral+row.qtd_geral_checkin} gerais</p><p className="text-xs font-semibold">{row.qtd_geral_checkin} com check-in · carga {Math.round(Number(row.ocupacao_carga_pct))}%</p>{row.freelancers_escalados>0?<p className="mt-2 inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-800"><CheckCircle2 className="h-3.5 w-3.5"/>Reforço já escalado ({row.freelancers_escalados})</p>:row.nivel!=="verde"&&<p className="mt-2 flex items-center gap-1 text-xs font-bold"><AlertTriangle className="h-4 w-4"/>Considere chamar reforço.</p>}</Card>):<Card className="p-4 sm:col-span-2"><p className="text-sm text-slate-500">A previsão ainda não foi calculada.</p></Card>}</div></section>}