import { useState } from "react";
import { Edit3, Plus, Save, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { GRUPOS, type Categoria, type FinConfig, type Fornecedor } from "@/lib/financeiro";

type Base={categorias:Categoria[];fornecedores:Fornecedor[];config:FinConfig|null;refresh:()=>void};
export function FornecedoresPanel({categorias,fornecedores,refresh}:Base){const [editing,setEditing]=useState<Fornecedor|null>(null);const [form,setForm]=useState({nome:"",cnpj_cpf:"",categoria_padrao_id:"",contato:"",telefone:"",chave_pix:"",observacoes:""}); const reset=(f?:Fornecedor)=>{setEditing(f??null);setForm(f?{nome:f.nome,cnpj_cpf:f.cnpj_cpf??"",categoria_padrao_id:f.categoria_padrao_id??"",contato:f.contato??"",telefone:f.telefone??"",chave_pix:f.chave_pix??"",observacoes:f.observacoes??""}:{nome:"",cnpj_cpf:"",categoria_padrao_id:"",contato:"",telefone:"",chave_pix:"",observacoes:""})}; async function save(){if(!form.nome.trim())return toast.error("Informe o nome do fornecedor.");const payload={...form,nome:form.nome.trim(),categoria_padrao_id:form.categoria_padrao_id||null,cnpj_cpf:form.cnpj_cpf||null,contato:form.contato||null,telefone:form.telefone||null,chave_pix:form.chave_pix||null,observacoes:form.observacoes||null};const {error}=editing?await supabase.from("fin_fornecedores").update(payload).eq("id",editing.id):await supabase.from("fin_fornecedores").insert(payload);if(error)return toast.error(error.message);toast.success("Fornecedor salvo");reset();refresh()}
 return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-3">{fornecedores.map(f=><Card key={f.id} className={!f.ativo?"opacity-60":""}><CardContent className="flex items-start justify-between gap-3 p-4"><div><p className="font-bold">{f.nome}</p><p className="text-sm text-muted-foreground">{f.cnpj_cpf||"Documento não informado"}{f.telefone?` · ${f.telefone}`:""}</p></div><div className="flex items-center gap-2"><Switch checked={f.ativo} onCheckedChange={async ativo=>{const {error}=await supabase.from("fin_fornecedores").update({ativo}).eq("id",f.id);if(error)toast.error(error.message);else refresh()}} aria-label={`Ativar ${f.nome}`} /><Button size="icon" variant="ghost" onClick={()=>reset(f)} aria-label={`Editar ${f.nome}`}><Edit3 /></Button></div></CardContent></Card>)}{!fornecedores.length&&<Empty text="Nenhum fornecedor cadastrado." />}</div><Card><CardHeader><CardTitle className="text-base">{editing?"Editar fornecedor":"Novo fornecedor"}</CardTitle></CardHeader><CardContent className="space-y-3"><Field label="Nome"><Input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></Field><Field label="CNPJ ou CPF"><Input value={form.cnpj_cpf} onChange={e=>setForm({...form,cnpj_cpf:e.target.value})}/></Field><Field label="Categoria padrão"><Select value={form.categoria_padrao_id||"none"} onValueChange={v=>setForm({...form,categoria_padrao_id:v==="none"?"":v})}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem categoria</SelectItem>{categorias.filter(c=>c.ativo).map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select></Field><Field label="Contato"><Input value={form.contato} onChange={e=>setForm({...form,contato:e.target.value})}/></Field><Field label="Telefone"><Input value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})}/></Field><Field label="Chave PIX"><Input value={form.chave_pix} onChange={e=>setForm({...form,chave_pix:e.target.value})}/></Field><Field label="Observações"><Textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></Field><div className="flex gap-2"><Button onClick={save}><Save/>Salvar</Button>{editing&&<Button variant="outline" onClick={()=>reset()}>Cancelar</Button>}</div></CardContent></Card></div>}
export function CategoriasPanel({categorias,config,refresh}:Base){const [editing,setEditing]=useState<Categoria|null>(null);const [nome,setNome]=useState("");const [grupo,setGrupo]=useState("administrativo");const [tipo,setTipo]=useState("despesa");const [bota,setBota]=useState(String(config?.rateio_botafogo_pct??61.3));const [ipa,setIpa]=useState(String(config?.rateio_ipanema_pct??38.7));async function saveCategory(){if(!nome.trim())return toast.error("Informe o nome da categoria.");const payload={nome:nome.trim(),grupo,tipo,ordem:editing?.ordem??categorias.length*10+10};const {error}=editing?await supabase.from("fin_categorias").update(payload).eq("id",editing.id):await supabase.from("fin_categorias").insert(payload);if(error)return toast.error(error.message);toast.success("Categoria salva");setNome("");setEditing(null);refresh()}async function saveRateio(){if(Math.abs(Number(bota)+Number(ipa)-100)>0.001)return toast.error("O rateio deve somar 100%.");const {error}=await supabase.from("fin_config").upsert({id:1,rateio_botafogo_pct:Number(bota),rateio_ipanema_pct:Number(ipa)});if(error)toast.error(error.message);else{toast.success("Rateio atualizado");refresh()}}
 return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-5">{Object.entries(GRUPOS).map(([key,label])=>{const items=categorias.filter(c=>c.grupo===key);if(!items.length)return null;return <section key={key}><h3 className="mb-2 text-xs font-bold uppercase text-muted-foreground">{label}</h3><div className="space-y-2">{items.map(c=><Card key={c.id} className={!c.ativo?"opacity-60":""}><CardContent className="flex items-center justify-between gap-3 p-3"><div><p className="font-semibold">{c.nome}</p><p className="text-xs text-muted-foreground">{c.tipo==="receita"?"Receita":"Despesa"}</p></div><div className="flex items-center gap-2"><Switch checked={c.ativo} onCheckedChange={async ativo=>{const {error}=await supabase.from("fin_categorias").update({ativo}).eq("id",c.id);if(error)toast.error(error.message);else refresh()}} aria-label={`Ativar ${c.nome}`}/><Button size="icon" variant="ghost" onClick={()=>{setEditing(c);setNome(c.nome);setGrupo(c.grupo);setTipo(c.tipo)}}><Edit3/></Button></div></CardContent></Card>)}</div></section>})}</div><div className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Plus/> {editing?"Editar categoria":"Nova categoria"}</CardTitle></CardHeader><CardContent className="space-y-3"><Field label="Nome"><Input value={nome} onChange={e=>setNome(e.target.value)}/></Field><Field label="Grupo"><Select value={grupo} onValueChange={setGrupo}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(GRUPOS).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></Field><Field label="Tipo"><Select value={tipo} onValueChange={setTipo} disabled={!!editing}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="despesa">Despesa</SelectItem><SelectItem value="receita">Receita</SelectItem></SelectContent></Select></Field><Button onClick={saveCategory}><Save/>Salvar</Button>{editing&&<Button className="ml-2" variant="outline" onClick={()=>{setEditing(null);setNome("")}}>Cancelar</Button>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2/>Rateio de custos compartilhados</CardTitle></CardHeader><CardContent className="space-y-3"><Field label="Botafogo (%)"><Input type="number" step="0.1" value={bota} onChange={e=>setBota(e.target.value)}/></Field><Field label="Ipanema (%)"><Input type="number" step="0.1" value={ipa} onChange={e=>setIpa(e.target.value)}/></Field><Button onClick={saveRateio}><Save/>Salvar rateio</Button></CardContent></Card></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}function Empty({text}:{text:string}){return <div className="border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>}
