import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Banknote, CalendarCheck, Copy, Download, Edit3, Eye, FileSpreadsheet, Loader2, Plus, Search, Trash2, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { currency, dateBR, FORMAS, monthNext, monthNow, openFinanceFile, statusReal, STATUS, valorRateado, type Categoria, type FinConfig, type Fornecedor, type FiltroUnidade, type Lancamento } from "@/lib/financeiro";
import { useFuncionarios } from "@/lib/store";
import { LancamentoDialog } from "./lancamento-dialog";
import { CategoriasPanel, FornecedoresPanel } from "./cadastros-financeiros";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type Loaded={categorias:Categoria[];fornecedores:Fornecedor[];lancamentos:Lancamento[];config:FinConfig|null};
export function FinanceiroPage(){const qc=useQueryClient();const {data:funcionarios=[]}=useFuncionarios();const [month,setMonth]=useState(monthNow());const [unit,setUnit]=useState<FiltroUnidade>("Consolidado");const [cat,setCat]=useState("all");const [status,setStatus]=useState("all");const [search,setSearch]=useState("");const [dialog,setDialog]=useState<{tipo:"despesa"|"receita";current?:Lancamento|null}|null>(null);const [pay,setPay]=useState<Lancamento|null>(null);
 const q=useQuery({queryKey:["financeiro"],queryFn:async():Promise<Loaded>=>{const [c,f,l,cfg]=await Promise.all([supabase.from("fin_categorias").select("*").order("ordem"),supabase.from("fin_fornecedores").select("*").order("nome"),supabase.from("fin_lancamentos").select("*").order("data_vencimento",{ascending:true}),supabase.from("fin_config").select("*").eq("id",1).maybeSingle()]);for(const r of [c,f,l,cfg])if(r.error)throw r.error;return{categorias:c.data??[],fornecedores:f.data??[],lancamentos:l.data??[],config:cfg.data}}});const data=q.data;const refresh=()=>qc.invalidateQueries({queryKey:["financeiro"]});
 const rows=useMemo(()=>{if(!data)return[];const text=search.trim().toLowerCase();return data.lancamentos.filter(l=>l.competencia.startsWith(month)).filter(l=>unit==="Consolidado"||l.unidade===unit||l.unidade==="Ambas").filter(l=>cat==="all"||l.categoria_id===cat).filter(l=>status==="all"||statusReal(l)===status).filter(l=>!text||l.descricao.toLowerCase().includes(text)||(data.fornecedores.find(f=>f.id===l.fornecedor_id)?.nome.toLowerCase().includes(text)??false));},[data,month,unit,cat,status,search]);
 const total=(filter?:(l:Lancamento)=>boolean)=>rows.filter(l=>l.status!=="cancelado"&&(!filter||filter(l))).reduce((s,l)=>s+valorRateado(l,unit,data?.config??null),0);
 async function remove(l:Lancamento){if(!confirm(`Excluir “${l.descricao}”?`))return;const {error}=await supabase.from("fin_lancamentos").delete().eq("id",l.id);if(error)return toast.error(error.message);if(l.anexo_path)await supabase.storage.from("financeiro").remove([l.anexo_path]);toast.success("Lançamento excluído");refresh()}
 async function duplicate(l:Lancamento){const {id,created_at,updated_at,...base}=l;const {error}=await supabase.from("fin_lancamentos").insert({...base,competencia:monthNext(l.competencia),data_pagamento:null,forma_pagamento:null,status:l.status==="cancelado"?"previsto":"a_pagar",recorrencia_id:l.recorrencia_id??id,anexo_path:null});if(error)toast.error(error.message);else{toast.success("Duplicado para o próximo mês");refresh()}}
 function exportRows(){return rows.map(l=>[dateBR(l.data_vencimento),l.descricao,data?.categorias.find(c=>c.id===l.categoria_id)?.nome??"",data?.fornecedores.find(f=>f.id===l.fornecedor_id)?.nome??"",l.unidade,STATUS[statusReal(l)],currency.format(valorRateado(l,unit,data?.config??null))])}
 function exportCsv(){const table=[["Vencimento","Descrição","Categoria","Fornecedor","Unidade","Situação","Valor"],...exportRows()];const csv=table.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");downloadBlob(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),`financeiro-${month}.csv`)}
 function exportPdf(){const doc=new jsPDF({orientation:"landscape"});doc.setFontSize(16);doc.text(`Financeiro · ${month.split("-").reverse().join("/")} · ${unit}`,14,16);autoTable(doc,{head:[["Venc.","Descrição","Categoria","Fornecedor","Unidade","Situação","Valor"]],body:exportRows(),startY:22,styles:{fontSize:8},foot:[["","","","","","Total",currency.format(total())]]});doc.save(`financeiro-${month}.pdf`)}
 if(q.isLoading)return <div className="grid min-h-72 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-primary"/></div>;if(q.isError)return <Card><CardContent className="p-8 text-center"><p className="font-bold text-destructive">Não foi possível carregar o Financeiro.</p><Button className="mt-4" onClick={()=>q.refetch()}>Tentar novamente</Button></CardContent></Card>;
 return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Área do Gestor</p><h2 className="text-2xl font-black text-slate-950">Financeiro</h2><p className="text-sm text-slate-500">Despesas, receitas, fornecedores e custos compartilhados.</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>setDialog({tipo:"despesa"})}><Plus/>Nova despesa</Button><Button variant="outline" onClick={()=>setDialog({tipo:"receita"})}><Plus/>Nova receita</Button></div></div>
 <Tabs defaultValue="lancamentos"><TabsList className="grid h-auto w-full grid-cols-2 gap-1 lg:grid-cols-4"><TabsTrigger value="lancamentos">Lançamentos</TabsTrigger><TabsTrigger value="fornecedores">Fornecedores</TabsTrigger><TabsTrigger value="categorias">Categorias</TabsTrigger><TabsTrigger value="exportar">Exportar</TabsTrigger></TabsList>
 <TabsContent value="lancamentos" className="space-y-4"><div className="grid gap-2 rounded-lg border bg-card p-3 sm:grid-cols-2 xl:grid-cols-5"><Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><Select value={unit} onValueChange={v=>setUnit(v as FiltroUnidade)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Consolidado","Botafogo","Ipanema"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={cat} onValueChange={setCat}><SelectTrigger><SelectValue placeholder="Categoria"/></SelectTrigger><SelectContent><SelectItem value="all">Todas as categorias</SelectItem>{data?.categorias.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue placeholder="Situação"/></SelectTrigger><SelectContent><SelectItem value="all">Todas as situações</SelectItem>{["previsto","a_pagar","vencido","pago","cancelado"].map(v=><SelectItem key={v} value={v}>{STATUS[v]}</SelectItem>)}</SelectContent></Select><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar"/></div></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Total icon={WalletCards} label="Total do filtro" value={total()}/><Total icon={CalendarCheck} label="Pago" value={total(l=>l.status==="pago")}/><Total icon={Banknote} label="A pagar" value={total(l=>l.status==="a_pagar"&&statusReal(l)!=="vencido")}/><Total icon={Banknote} label="Vencido" value={total(l=>statusReal(l)==="vencido")} danger/></div>
 <div className="space-y-3 md:hidden">{rows.map(l=><MobileRow key={l.id} l={l} data={data} value={valorRateado(l,unit,data?.config??null)} edit={()=>setDialog({tipo:l.tipo as "despesa"|"receita",current:l})} pay={()=>setPay(l)} duplicate={()=>duplicate(l)} remove={()=>remove(l)}/>)}</div>
 <Card className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Vencimento</TableHead><TableHead>Descrição</TableHead><TableHead>Categoria / fornecedor</TableHead><TableHead>Unidade</TableHead><TableHead>Situação</TableHead><TableHead className="text-right">Valor</TableHead><TableHead className="w-40">Ações</TableHead></TableRow></TableHeader><TableBody>{rows.map(l=><TableRow key={l.id}><TableCell>{dateBR(l.data_vencimento)}</TableCell><TableCell className="font-semibold">{l.descricao}</TableCell><TableCell><p>{data?.categorias.find(c=>c.id===l.categoria_id)?.nome}</p><p className="text-xs text-muted-foreground">{data?.fornecedores.find(f=>f.id===l.fornecedor_id)?.nome??"—"}</p></TableCell><TableCell>{l.unidade}</TableCell><TableCell><StatusBadge value={statusReal(l)}/></TableCell><TableCell className="text-right font-bold">{currency.format(valorRateado(l,unit,data?.config??null))}</TableCell><TableCell><Actions l={l} edit={()=>setDialog({tipo:l.tipo as "despesa"|"receita",current:l})} pay={()=>setPay(l)} duplicate={()=>duplicate(l)} remove={()=>remove(l)}/></TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={7} className="py-12 text-center text-muted-foreground">Nenhum lançamento neste filtro.</TableCell></TableRow>}</TableBody></Table></Card></TabsContent>
 <TabsContent value="fornecedores"><FornecedoresPanel categorias={data?.categorias??[]} fornecedores={data?.fornecedores??[]} config={data?.config??null} refresh={refresh}/></TabsContent><TabsContent value="categorias"><CategoriasPanel categorias={data?.categorias??[]} fornecedores={data?.fornecedores??[]} config={data?.config??null} refresh={refresh}/></TabsContent><TabsContent value="exportar"><Card><CardContent className="space-y-5 p-6"><div><h3 className="text-lg font-bold">Exportar filtro atual</h3><p className="text-sm text-muted-foreground">Serão exportados {rows.length} lançamentos de {month.split("-").reverse().join("/")} · {unit}.</p></div><div className="flex flex-wrap gap-3"><Button onClick={exportCsv}><FileSpreadsheet/>Baixar CSV</Button><Button variant="outline" onClick={exportPdf}><Download/>Baixar PDF</Button></div></CardContent></Card></TabsContent></Tabs>
 {dialog&&<LancamentoDialog open onOpenChange={v=>!v&&setDialog(null)} tipo={dialog.tipo} current={dialog.current} categorias={data?.categorias??[]} fornecedores={data?.fornecedores??[]} funcionarios={funcionarios} onSaved={refresh}/>}<PayDialog item={pay} close={()=>setPay(null)} saved={refresh}/></div>}
function Total({icon:Icon,label,value,danger=false}:{icon:typeof Banknote;label:string;value:number;danger?:boolean}){return <Card><CardContent className="p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground"><Icon className={danger?"text-destructive":"text-primary"}/>{label}</div><p className={danger?"mt-2 text-xl font-black text-destructive":"mt-2 text-xl font-black"}>{currency.format(value)}</p></CardContent></Card>}
function StatusBadge({value}:{value:string}){const cls=value==="pago"?"bg-emerald-100 text-emerald-800":value==="vencido"?"bg-red-100 text-red-800":value==="a_pagar"?"bg-blue-100 text-blue-800":"bg-slate-100 text-slate-700";return <span className={`inline-flex rounded-full px-2 py-1 text-xs font-bold ${cls}`}>{STATUS[value]}</span>}
function Actions({l,edit,pay,duplicate,remove}:{l:Lancamento;edit:()=>void;pay:()=>void;duplicate:()=>void;remove:()=>void}){return <div className="flex gap-1">{l.anexo_path&&<Button size="icon" variant="ghost" title="Ver comprovante" onClick={()=>openFinanceFile(l.anexo_path??"").catch(e=>toast.error(e.message))}><Eye/></Button>}{l.status!=="pago"&&l.status!=="cancelado"&&<Button size="icon" variant="ghost" title="Marcar como pago" onClick={pay}><CalendarCheck/></Button>}<Button size="icon" variant="ghost" title="Editar" onClick={edit}><Edit3/></Button><Button size="icon" variant="ghost" title="Duplicar" onClick={duplicate}><Copy/></Button><Button size="icon" variant="ghost" title="Excluir" onClick={remove}><Trash2/></Button></div>}
function MobileRow({l,data,value,edit,pay,duplicate,remove}:{l:Lancamento;data:Loaded|undefined;value:number;edit:()=>void;pay:()=>void;duplicate:()=>void;remove:()=>void}){return <Card><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{l.descricao}</p><p className="text-xs text-muted-foreground">{data?.categorias.find(c=>c.id===l.categoria_id)?.nome} · {dateBR(l.data_vencimento)}</p></div><StatusBadge value={statusReal(l)}/></div><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{l.unidade}</span><span className="text-lg font-black">{currency.format(value)}</span></div><Actions l={l} edit={edit} pay={pay} duplicate={duplicate} remove={remove}/></CardContent></Card>}
function PayDialog({item,close,saved}:{item:Lancamento|null;close:()=>void;saved:()=>void}){const [date,setDate]=useState("");const [form,setForm]=useState("pix");async function save(){if(!item)return;const {error}=await supabase.from("fin_lancamentos").update({status:"pago",data_pagamento:date,forma_pagamento:form}).eq("id",item.id);if(error)toast.error(error.message);else{toast.success("Pagamento registrado");saved();close()}}return <Dialog open={!!item} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Marcar como pago</DialogTitle><DialogDescription>{item?.descricao}</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Data do pagamento</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="space-y-2"><Label>Forma</Label><Select value={form} onValueChange={setForm}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(FORMAS).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={close}>Cancelar</Button><Button disabled={!date} onClick={save}>Confirmar</Button></DialogFooter></DialogContent></Dialog>}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
