import { useEffect, useRef, useState } from "react";
import { Camera, FileUp, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { FORMAS, monthNow, uploadFinanceFile, type Categoria, type Fornecedor, type Lancamento, type TipoLancamento } from "@/lib/financeiro";
import type { Funcionario } from "@/lib/store";

type Props = { open: boolean; onOpenChange:(v:boolean)=>void; tipo:TipoLancamento; categorias:Categoria[]; fornecedores:Fornecedor[]; funcionarios:Funcionario[]; current?:Lancamento|null; onSaved:()=>void };
const EMPTY_ID="__none";
export function LancamentoDialog({open,onOpenChange,tipo,categorias,fornecedores,funcionarios,current,onSaved}:Props){
 const [saving,setSaving]=useState(false); const [file,setFile]=useState<File|null>(null); const cameraRef=useRef<HTMLInputElement>(null); const fileRef=useRef<HTMLInputElement>(null);
 const [form,setForm]=useState({unidade:"Botafogo",categoria_id:"",fornecedor_id:"",descricao:"",valor:"",competencia:monthNow(),data_vencimento:"",data_pagamento:"",status:"a_pagar",forma_pagamento:"",numero_documento:"",consumo_quantidade:"",consumo_unidade:"kWh",funcionario_id:"",freelancer_nome:"",qtd_diarias:"",ativo_descricao:"",observacoes:""});
 useEffect(()=>{ if(!open)return; setFile(null); setForm(current?{unidade:current.unidade,categoria_id:current.categoria_id,fornecedor_id:current.fornecedor_id??"",descricao:current.descricao,valor:String(current.valor),competencia:current.competencia.slice(0,7),data_vencimento:current.data_vencimento??"",data_pagamento:current.data_pagamento??"",status:current.status,forma_pagamento:current.forma_pagamento??"",numero_documento:current.numero_documento??"",consumo_quantidade:current.consumo_quantidade?String(current.consumo_quantidade):"",consumo_unidade:current.consumo_unidade??"kWh",funcionario_id:current.funcionario_id??"",freelancer_nome:current.freelancer_nome??"",qtd_diarias:current.qtd_diarias?String(current.qtd_diarias):"",ativo_descricao:current.ativo_descricao??"",observacoes:current.observacoes??""}:{unidade:"Botafogo",categoria_id:categorias.find(c=>c.tipo===tipo&&c.ativo)?.id??"",fornecedor_id:"",descricao:"",valor:"",competencia:monthNow(),data_vencimento:"",data_pagamento:"",status:tipo==="receita"?"previsto":"a_pagar",forma_pagamento:"",numero_documento:"",consumo_quantidade:"",consumo_unidade:"kWh",funcionario_id:"",freelancer_nome:"",qtd_diarias:"",ativo_descricao:"",observacoes:""}); },[open,current,tipo,categorias]);
 const category=categorias.find(c=>c.id===form.categoria_id); const isConsumption=/Água|Energia/i.test(category?.nome??""); const isSalary=/Salários/i.test(category?.nome??""); const isFreelancer=/Freelancers/i.test(category?.nome??""); const isMaintenance=category?.grupo==="manutencao";
 const set=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 async function save(){ if(!form.descricao.trim()||!form.categoria_id||Number(form.valor)<=0){toast.error("Preencha descrição, categoria e valor válido.");return;} if(form.status==="pago"&&(!form.data_pagamento||!form.forma_pagamento)){toast.error("Informe a data e a forma de pagamento.");return;} setSaving(true); try { let anexo=current?.anexo_path??null; if(file) anexo=await uploadFinanceFile(file); const payload={tipo,unidade:form.unidade,categoria_id:form.categoria_id,fornecedor_id:form.fornecedor_id||null,descricao:form.descricao.trim(),valor:Number(form.valor),competencia:`${form.competencia}-01`,data_vencimento:form.data_vencimento||null,data_pagamento:form.status==="pago"?form.data_pagamento:null,status:form.status,forma_pagamento:form.status==="pago"?form.forma_pagamento:null,numero_documento:form.numero_documento.trim()||null,anexo_path:anexo,consumo_quantidade:isConsumption&&form.consumo_quantidade?Number(form.consumo_quantidade):null,consumo_unidade:isConsumption?form.consumo_unidade:null,funcionario_id:isSalary&&form.funcionario_id?form.funcionario_id:null,freelancer_nome:isFreelancer?form.freelancer_nome.trim()||null:null,qtd_diarias:isFreelancer&&form.qtd_diarias?Number(form.qtd_diarias):null,ativo_descricao:isMaintenance?form.ativo_descricao.trim()||null:null,observacoes:form.observacoes.trim()||null}; const q=current?supabase.from("fin_lancamentos").update(payload).eq("id",current.id):supabase.from("fin_lancamentos").insert(payload); const {error}=await q;if(error)throw error; toast.success(current?"Lançamento atualizado":"Lançamento criado"); onSaved();onOpenChange(false); }catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar o lançamento.");}finally{setSaving(false)} }
 const cats=categorias.filter(c=>c.tipo===tipo&&(c.ativo||c.id===current?.categoria_id));
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{current?"Editar":tipo==="despesa"?"Nova despesa":"Nova receita"}</DialogTitle><DialogDescription>Preencha os dados financeiros e anexe o comprovante, se houver.</DialogDescription></DialogHeader>
 <div className="grid gap-4 sm:grid-cols-2">
  <Field label="Descrição"><Input value={form.descricao} onChange={e=>set("descricao",e.target.value)} /></Field><Field label="Valor (R$)"><Input type="number" min="0.01" step="0.01" value={form.valor} onChange={e=>set("valor",e.target.value)} /></Field>
  <Field label="Unidade"><Select value={form.unidade} onValueChange={v=>set("unidade",v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Botafogo","Ipanema","Ambas"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field>
  <Field label="Categoria"><Select value={form.categoria_id} onValueChange={v=>set("categoria_id",v)}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{cats.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select></Field>
  <Field label="Fornecedor"><Select value={form.fornecedor_id||EMPTY_ID} onValueChange={v=>set("fornecedor_id",v===EMPTY_ID?"":v)}><SelectTrigger><SelectValue placeholder="Opcional" /></SelectTrigger><SelectContent><SelectItem value={EMPTY_ID}>Sem fornecedor</SelectItem>{fornecedores.filter(f=>f.ativo||f.id===current?.fornecedor_id).map(f=><SelectItem key={f.id} value={f.id}>{f.nome}</SelectItem>)}</SelectContent></Select></Field>
  <Field label="Competência"><Input type="month" value={form.competencia} onChange={e=>set("competencia",e.target.value)} /></Field><Field label="Vencimento"><Input type="date" value={form.data_vencimento} onChange={e=>set("data_vencimento",e.target.value)} /></Field>
  <Field label="Situação"><Select value={form.status} onValueChange={v=>set("status",v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="previsto">Previsto</SelectItem><SelectItem value="a_pagar">A pagar</SelectItem><SelectItem value="pago">Pago</SelectItem><SelectItem value="cancelado">Cancelado</SelectItem></SelectContent></Select></Field>
  {form.status==="pago"&&<><Field label="Data do pagamento"><Input type="date" value={form.data_pagamento} onChange={e=>set("data_pagamento",e.target.value)} /></Field><Field label="Forma de pagamento"><Select value={form.forma_pagamento} onValueChange={v=>set("forma_pagamento",v)}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{Object.entries(FORMAS).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></Field></>}
  <Field label="Número do documento"><Input value={form.numero_documento} onChange={e=>set("numero_documento",e.target.value)} /></Field>
  {isConsumption&&<><Field label="Consumo"><Input type="number" min="0" step="0.01" value={form.consumo_quantidade} onChange={e=>set("consumo_quantidade",e.target.value)} /></Field><Field label="Unidade de consumo"><Select value={form.consumo_unidade} onValueChange={v=>set("consumo_unidade",v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="kWh">kWh</SelectItem><SelectItem value="m³">m³</SelectItem></SelectContent></Select></Field></>}
  {isSalary&&<Field label="Funcionário"><Select value={form.funcionario_id||EMPTY_ID} onValueChange={v=>set("funcionario_id",v===EMPTY_ID?"":v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value={EMPTY_ID}>Selecione</SelectItem>{funcionarios.map(f=><SelectItem key={f.id} value={f.id}>{f.nome}</SelectItem>)}</SelectContent></Select></Field>}
  {isFreelancer&&<><Field label="Freelancer"><Input value={form.freelancer_nome} onChange={e=>set("freelancer_nome",e.target.value)} /></Field><Field label="Quantidade de diárias"><Input type="number" min="1" value={form.qtd_diarias} onChange={e=>set("qtd_diarias",e.target.value)} /></Field></>}
  {isMaintenance&&<Field label="Equipamento ou local"><Input value={form.ativo_descricao} onChange={e=>set("ativo_descricao",e.target.value)} placeholder="Ex.: AC quarto 204" /></Field>}
  <Field label="Observações" wide><Textarea value={form.observacoes} onChange={e=>set("observacoes",e.target.value)} /></Field>
  <div className="sm:col-span-2"><Label>Comprovante ou nota</Label><div className="mt-2 flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={()=>cameraRef.current?.click()}><Camera /> Tirar foto</Button><Button type="button" variant="outline" onClick={()=>fileRef.current?.click()}><FileUp /> Escolher imagem ou PDF</Button>{file&&<span className="self-center text-sm text-muted-foreground">{file.name}</span>}{!file&&current?.anexo_path&&<span className="self-center text-sm text-muted-foreground">Comprovante já anexado</span>}</div><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]??null)} /><input ref={fileRef} hidden type="file" accept="image/*,application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)} /></div>
 </div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving&&<Loader2 className="animate-spin" />} Salvar</Button></DialogFooter></DialogContent></Dialog>;
}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={wide?"space-y-2 sm:col-span-2":"space-y-2"}><Label>{label}</Label>{children}</div>}
