import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useMinhaEscala } from "@/lib/escala";
import { monthBounds } from "@/lib/escala-engine";
import { todaySP } from "@/lib/tz";
const MONTHS=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const labels:Record<string,string>={trabalho:"Trabalho",folga:"Folga",falta:"Falta",atestado:"Atestado",ferias:"Férias",extra:"Plantão extra"};
export const Route=createFileRoute("/_authenticated/minha-escala")({head:()=>({meta:[{title:"Minha Escala — INJOY"},{name:"description",content:"Consulte seus plantões publicados no INJOY."},{property:"og:title",content:"Minha Escala — INJOY"},{property:"og:description",content:"Consulte seus plantões publicados no INJOY."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:MinhaEscala});
function MinhaEscala(){const now=todaySP(),[year,setYear]=useState(Number(now.slice(0,4))),[month,setMonth]=useState(Number(now.slice(5,7))-1);const b=monthBounds(year,month),q=useMinhaEscala(b.start,b.end);const change=(n:number)=>{let m=month+n,y=year;if(m<0){m=11;y--}if(m>11){m=0;y++}setMonth(m);setYear(y)};return <div className="space-y-5"><header><Badge variant="secondary" className="mb-2"><CalendarDays className="mr-1 h-3 w-3"/>Equipe</Badge><h1 className="text-2xl font-bold">Minha Escala</h1><p className="text-sm text-muted-foreground">Seus plantões publicados pela gestão.</p></header><div className="flex items-center gap-2"><Button size="icon" variant="outline" onClick={()=>change(-1)}><ChevronLeft className="h-4 w-4"/></Button><div className="min-w-40 rounded-md border px-3 py-2 text-center text-sm font-medium">{MONTHS[month]} / {year}</div><Button size="icon" variant="outline" onClick={()=>change(1)}><ChevronRight className="h-4 w-4"/></Button></div>{q.isLoading?<p>Carregando…</p>:!q.data?.length?<Card className="p-6 text-center text-sm text-muted-foreground">Nenhuma escala publicada para este mês.</Card>:<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{q.data.map(d=><Card key={d.id} className="p-4"><div className="flex items-center justify-between"><strong>{d.data.split("-").reverse().join("/")}</strong><Badge variant={d.status==="trabalho"||d.status==="extra"?"default":"secondary"}>{labels[d.status]??d.status}</Badge></div><p className="mt-2 text-sm">{d.unidade} · {d.setor}</p><p className="text-sm text-muted-foreground">{d.turno}{d.hora_entrada?` · ${d.hora_entrada.slice(0,5)}${d.hora_saida?`–${d.hora_saida.slice(0,5)}`:""}`:""}</p>{d.motivo&&<p className="mt-2 text-xs text-muted-foreground">{d.motivo}</p>}</Card>)}</div>}</div>}
