/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AuthenticatedVistoriaRouteImport } from './routes/_authenticated/vistoria'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedRecepcaoRouteImport } from './routes/_authenticated/recepcao'
import { Route as AuthenticatedPreventivaRouteImport } from './routes/_authenticated/preventiva'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedHistoricoLimpezaRouteImport } from './routes/_authenticated/historico-limpeza'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedEscalaRouteImport } from './routes/_authenticated/escala'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCamareirasRouteImport } from './routes/_authenticated/camareiras'
import { Route as ApiPublicCloudbedsWebhookRouteImport } from './routes/api/public/cloudbeds-webhook'
import { Route as AuthenticatedChamadosIdRouteImport } from './routes/_authenticated/chamados.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedVistoriaRoute = AuthenticatedVistoriaRouteImport.update({
  id: '/vistoria',
  path: '/vistoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecepcaoRoute = AuthenticatedRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreventivaRoute = AuthenticatedPreventivaRouteImport.update({
  id: '/preventiva',
  path: '/preventiva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoLimpezaRoute =
  AuthenticatedHistoricoLimpezaRouteImport.update({
    id: '/historico-limpeza',
    path: '/historico-limpeza',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalaRoute = AuthenticatedEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCamareirasRoute = AuthenticatedCamareirasRouteImport.update({
  id: '/camareiras',
  path: '/camareiras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCloudbedsWebhookRoute =
  ApiPublicCloudbedsWebhookRouteImport.update({
    id: '/api/public/cloudbeds-webhook',
    path: '/api/public/cloudbeds-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChamadosIdRoute = AuthenticatedChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/camareiras': typeof AuthenticatedCamareirasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/historico-limpeza': typeof AuthenticatedHistoricoLimpezaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/vistoria': typeof AuthenticatedVistoriaRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/': typeof AuthIndexRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/api/public/cloudbeds-webhook': typeof ApiPublicCloudbedsWebhookRoute
}
export interface FileRoutesByTo {
  '/camareiras': typeof AuthenticatedCamareirasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/historico-limpeza': typeof AuthenticatedHistoricoLimpezaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/vistoria': typeof AuthenticatedVistoriaRoute
  '/auth/admin': typeof AuthAdminRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/api/public/cloudbeds-webhook': typeof ApiPublicCloudbedsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/camareiras': typeof AuthenticatedCamareirasRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/escala': typeof AuthenticatedEscalaRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/historico-limpeza': typeof AuthenticatedHistoricoLimpezaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/preventiva': typeof AuthenticatedPreventivaRoute
  '/_authenticated/recepcao': typeof AuthenticatedRecepcaoRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/vistoria': typeof AuthenticatedVistoriaRoute
  '/auth/admin': typeof AuthAdminRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/api/public/cloudbeds-webhook': typeof ApiPublicCloudbedsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/camareiras'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/escala'
    | '/gestao'
    | '/historico-limpeza'
    | '/painel'
    | '/preventiva'
    | '/recepcao'
    | '/servicos'
    | '/vistoria'
    | '/auth/admin'
    | '/auth/'
    | '/chamados/$id'
    | '/api/public/cloudbeds-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/camareiras'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/escala'
    | '/gestao'
    | '/historico-limpeza'
    | '/painel'
    | '/preventiva'
    | '/recepcao'
    | '/servicos'
    | '/vistoria'
    | '/auth/admin'
    | '/'
    | '/auth'
    | '/chamados/$id'
    | '/api/public/cloudbeds-webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/camareiras'
    | '/_authenticated/chat'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/escala'
    | '/_authenticated/gestao'
    | '/_authenticated/historico-limpeza'
    | '/_authenticated/painel'
    | '/_authenticated/preventiva'
    | '/_authenticated/recepcao'
    | '/_authenticated/servicos'
    | '/_authenticated/vistoria'
    | '/auth/admin'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/chamados/$id'
    | '/api/public/cloudbeds-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicCloudbedsWebhookRoute: typeof ApiPublicCloudbedsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/vistoria': {
      id: '/_authenticated/vistoria'
      path: '/vistoria'
      fullPath: '/vistoria'
      preLoaderRoute: typeof AuthenticatedVistoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepcao': {
      id: '/_authenticated/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof AuthenticatedRecepcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preventiva': {
      id: '/_authenticated/preventiva'
      path: '/preventiva'
      fullPath: '/preventiva'
      preLoaderRoute: typeof AuthenticatedPreventivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-limpeza': {
      id: '/_authenticated/historico-limpeza'
      path: '/historico-limpeza'
      fullPath: '/historico-limpeza'
      preLoaderRoute: typeof AuthenticatedHistoricoLimpezaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala': {
      id: '/_authenticated/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof AuthenticatedEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/camareiras': {
      id: '/_authenticated/camareiras'
      path: '/camareiras'
      fullPath: '/camareiras'
      preLoaderRoute: typeof AuthenticatedCamareirasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cloudbeds-webhook': {
      id: '/api/public/cloudbeds-webhook'
      path: '/api/public/cloudbeds-webhook'
      fullPath: '/api/public/cloudbeds-webhook'
      preLoaderRoute: typeof ApiPublicCloudbedsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chamados/$id': {
      id: '/_authenticated/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof AuthenticatedChamadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCamareirasRoute: typeof AuthenticatedCamareirasRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEscalaRoute: typeof AuthenticatedEscalaRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedHistoricoLimpezaRoute: typeof AuthenticatedHistoricoLimpezaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPreventivaRoute: typeof AuthenticatedPreventivaRoute
  AuthenticatedRecepcaoRoute: typeof AuthenticatedRecepcaoRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedVistoriaRoute: typeof AuthenticatedVistoriaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChamadosIdRoute: typeof AuthenticatedChamadosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCamareirasRoute: AuthenticatedCamareirasRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEscalaRoute: AuthenticatedEscalaRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedHistoricoLimpezaRoute: AuthenticatedHistoricoLimpezaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPreventivaRoute: AuthenticatedPreventivaRoute,
  AuthenticatedRecepcaoRoute: AuthenticatedRecepcaoRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedVistoriaRoute: AuthenticatedVistoriaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChamadosIdRoute: AuthenticatedChamadosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicCloudbedsWebhookRoute: ApiPublicCloudbedsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
