/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAlmoxarifadoRouteImport } from './routes/_authenticated/almoxarifado'
import { Route as AuthenticatedBoasVindasRouteImport } from './routes/_authenticated/boas-vindas'
import { Route as AuthenticatedBonificacaoRouteImport } from './routes/_authenticated/bonificacao'
import { Route as AuthenticatedCamareirasRouteImport } from './routes/_authenticated/camareiras'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCheckInDigitalRouteImport } from './routes/_authenticated/check-in-digital'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedControlePontoRouteImport } from './routes/_authenticated/controle-ponto'
import { Route as AuthenticatedEscalaRouteImport } from './routes/_authenticated/escala'
import { Route as AuthenticatedEstoqueGeralRouteImport } from './routes/_authenticated/estoque-geral'
import { Route as AuthenticatedFrigobarRouteImport } from './routes/_authenticated/frigobar'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedGestaoBoasVindasRouteImport } from './routes/_authenticated/gestao-boas-vindas'
import { Route as AuthenticatedGestorRouteRouteImport } from './routes/_authenticated/gestor/route'
import { Route as AuthenticatedHistoricoCaixaRouteImport } from './routes/_authenticated/historico-caixa'
import { Route as AuthenticatedHistoricoLimpezaRouteImport } from './routes/_authenticated/historico-limpeza'
import { Route as AuthenticatedHistoricoManutencaoRouteImport } from './routes/_authenticated/historico-manutencao'
import { Route as AuthenticatedHistoricoVistoriasRouteImport } from './routes/_authenticated/historico-vistorias'
import { Route as AuthenticatedMinhaEscalaRouteImport } from './routes/_authenticated/minha-escala'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPontoRouteImport } from './routes/_authenticated/ponto'
import { Route as AuthenticatedPreventivaRouteImport } from './routes/_authenticated/preventiva'
import { Route as AuthenticatedPrevisaoCargaRouteImport } from './routes/_authenticated/previsao-carga'
import { Route as AuthenticatedRecepcaoRouteImport } from './routes/_authenticated/recepcao'
import { Route as AuthenticatedRelatorioOperacoesRouteImport } from './routes/_authenticated/relatorio-operacoes'
import { Route as AuthenticatedRelatoriosTurnoRouteImport } from './routes/_authenticated/relatorios-turno'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedVistoriaRouteImport } from './routes/_authenticated/vistoria'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AuthenticatedChamadosIdRouteImport } from './routes/_authenticated/chamados.$id'
import { Route as AuthenticatedGestorIndexRouteImport } from './routes/_authenticated/gestor/index'
import { Route as AuthenticatedGestorEscalaRouteImport } from './routes/_authenticated/gestor/escala'
import { Route as AuthenticatedGestorFinanceiroRouteImport } from './routes/_authenticated/gestor/financeiro'
import { Route as AuthenticatedGestorPontoRouteImport } from './routes/_authenticated/gestor/ponto'
import { Route as AuthenticatedGestorPrevisaoCargaRouteImport } from './routes/_authenticated/gestor/previsao-carga'
import { Route as AuthenticatedGestorTarefasExtrasRouteImport } from './routes/_authenticated/gestor/tarefas-extras'
import { Route as AuthenticatedGestorTotemRouteImport } from './routes/_authenticated/gestor/totem'
import { Route as ApiPublicBonusMetaRouteImport } from './routes/api/public/bonus-meta'
import { Route as ApiPublicCloudbedsWebhookRouteImport } from './routes/api/public/cloudbeds-webhook'
import { Route as ApiPublicPagarmeWebhookRouteImport } from './routes/api/public/pagarme-webhook'
import { Route as ApiPublicPrevisaoCargaRouteImport } from './routes/api/public/previsao-carga'
import { Route as ApiPublicPushDispatcherRouteImport } from './routes/api/public/push-dispatcher'
import { Route as ApiPublicTuyaCleanupRouteImport } from './routes/api/public/tuya-cleanup'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlmoxarifadoRoute =
  AuthenticatedAlmoxarifadoRouteImport.update({
    id: '/almoxarifado',
    path: '/almoxarifado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoasVindasRoute = AuthenticatedBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBonificacaoRoute =
  AuthenticatedBonificacaoRouteImport.update({
    id: '/bonificacao',
    path: '/bonificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCamareirasRoute = AuthenticatedCamareirasRouteImport.update({
  id: '/camareiras',
  path: '/camareiras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInDigitalRoute =
  AuthenticatedCheckInDigitalRouteImport.update({
    id: '/check-in-digital',
    path: '/check-in-digital',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlePontoRoute =
  AuthenticatedControlePontoRouteImport.update({
    id: '/controle-ponto',
    path: '/controle-ponto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscalaRoute = AuthenticatedEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueGeralRoute =
  AuthenticatedEstoqueGeralRouteImport.update({
    id: '/estoque-geral',
    path: '/estoque-geral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrigobarRoute = AuthenticatedFrigobarRouteImport.update({
  id: '/frigobar',
  path: '/frigobar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoBoasVindasRoute =
  AuthenticatedGestaoBoasVindasRouteImport.update({
    id: '/gestao-boas-vindas',
    path: '/gestao-boas-vindas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestorRouteRoute =
  AuthenticatedGestorRouteRouteImport.update({
    id: '/gestor',
    path: '/gestor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoCaixaRoute =
  AuthenticatedHistoricoCaixaRouteImport.update({
    id: '/historico-caixa',
    path: '/historico-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoLimpezaRoute =
  AuthenticatedHistoricoLimpezaRouteImport.update({
    id: '/historico-limpeza',
    path: '/historico-limpeza',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoManutencaoRoute =
  AuthenticatedHistoricoManutencaoRouteImport.update({
    id: '/historico-manutencao',
    path: '/historico-manutencao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoVistoriasRoute =
  AuthenticatedHistoricoVistoriasRouteImport.update({
    id: '/historico-vistorias',
    path: '/historico-vistorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaEscalaRoute =
  AuthenticatedMinhaEscalaRouteImport.update({
    id: '/minha-escala',
    path: '/minha-escala',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPontoRoute = AuthenticatedPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreventivaRoute = AuthenticatedPreventivaRouteImport.update({
  id: '/preventiva',
  path: '/preventiva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrevisaoCargaRoute =
  AuthenticatedPrevisaoCargaRouteImport.update({
    id: '/previsao-carga',
    path: '/previsao-carga',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecepcaoRoute = AuthenticatedRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioOperacoesRoute =
  AuthenticatedRelatorioOperacoesRouteImport.update({
    id: '/relatorio-operacoes',
    path: '/relatorio-operacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosTurnoRoute =
  AuthenticatedRelatoriosTurnoRouteImport.update({
    id: '/relatorios-turno',
    path: '/relatorios-turno',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVistoriaRoute = AuthenticatedVistoriaRouteImport.update({
  id: '/vistoria',
  path: '/vistoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedChamadosIdRoute = AuthenticatedChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestorIndexRoute =
  AuthenticatedGestorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorEscalaRoute =
  AuthenticatedGestorEscalaRouteImport.update({
    id: '/escala',
    path: '/escala',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorFinanceiroRoute =
  AuthenticatedGestorFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorPontoRoute =
  AuthenticatedGestorPontoRouteImport.update({
    id: '/ponto',
    path: '/ponto',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorPrevisaoCargaRoute =
  AuthenticatedGestorPrevisaoCargaRouteImport.update({
    id: '/previsao-carga',
    path: '/previsao-carga',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorTarefasExtrasRoute =
  AuthenticatedGestorTarefasExtrasRouteImport.update({
    id: '/tarefas-extras',
    path: '/tarefas-extras',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorTotemRoute =
  AuthenticatedGestorTotemRouteImport.update({
    id: '/totem',
    path: '/totem',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const ApiPublicBonusMetaRoute = ApiPublicBonusMetaRouteImport.update({
  id: '/api/public/bonus-meta',
  path: '/api/public/bonus-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudbedsWebhookRoute =
  ApiPublicCloudbedsWebhookRouteImport.update({
    id: '/api/public/cloudbeds-webhook',
    path: '/api/public/cloudbeds-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPagarmeWebhookRoute = ApiPublicPagarmeWebhookRouteImport.update({
  id: '/api/public/pagarme-webhook',
  path: '/api/public/pagarme-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrevisaoCargaRoute = ApiPublicPrevisaoCargaRouteImport.update({
  id: '/api/public/previsao-carga',
  path: '/api/public/previsao-carga',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatcherRoute = ApiPublicPushDispatcherRouteImport.update({
  id: '/api/public/push-dispatcher',
  path: '/api/public/push-dispatcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTuyaCleanupRoute = ApiPublicTuyaCleanupRouteImport.update({
  id: '/api/public/tuya-cleanup',
  path: '/api/public/tuya-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manutencao': typeof ManutencaoRoute
  '/totem': typeof TotemRoute
  '/gestor': typeof AuthenticatedGestorRouteRouteWithChildren
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/bonificacao': typeof AuthenticatedBonificacaoRoute
  '/camareiras': typeof AuthenticatedCamareirasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/check-in-digital': typeof AuthenticatedCheckInDigitalRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/controle-ponto': typeof AuthenticatedControlePontoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/estoque-geral': typeof AuthenticatedEstoqueGeralRoute
  '/frigobar': typeof AuthenticatedFrigobarRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/gestao-boas-vindas': typeof AuthenticatedGestaoBoasVindasRoute
  '/historico-caixa': typeof AuthenticatedHistoricoCaixaRoute
  '/historico-limpeza': typeof AuthenticatedHistoricoLimpezaRoute
  '/historico-manutencao': typeof AuthenticatedHistoricoManutencaoRoute
  '/historico-vistorias': typeof AuthenticatedHistoricoVistoriasRoute
  '/minha-escala': typeof AuthenticatedMinhaEscalaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/previsao-carga': typeof AuthenticatedPrevisaoCargaRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/relatorio-operacoes': typeof AuthenticatedRelatorioOperacoesRoute
  '/relatorios-turno': typeof AuthenticatedRelatoriosTurnoRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/vistoria': typeof AuthenticatedVistoriaRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/': typeof AuthIndexRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/gestor/escala': typeof AuthenticatedGestorEscalaRoute
  '/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/gestor/ponto': typeof AuthenticatedGestorPontoRoute
  '/gestor/previsao-carga': typeof AuthenticatedGestorPrevisaoCargaRoute
  '/gestor/tarefas-extras': typeof AuthenticatedGestorTarefasExtrasRoute
  '/gestor/totem': typeof AuthenticatedGestorTotemRoute
  '/api/public/bonus-meta': typeof ApiPublicBonusMetaRoute
  '/api/public/cloudbeds-webhook': typeof ApiPublicCloudbedsWebhookRoute
  '/api/public/pagarme-webhook': typeof ApiPublicPagarmeWebhookRoute
  '/api/public/previsao-carga': typeof ApiPublicPrevisaoCargaRoute
  '/api/public/push-dispatcher': typeof ApiPublicPushDispatcherRoute
  '/api/public/tuya-cleanup': typeof ApiPublicTuyaCleanupRoute
  '/gestor/': typeof AuthenticatedGestorIndexRoute
}
export interface FileRoutesByTo {
  '/manutencao': typeof ManutencaoRoute
  '/totem': typeof TotemRoute
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/bonificacao': typeof AuthenticatedBonificacaoRoute
  '/camareiras': typeof AuthenticatedCamareirasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/check-in-digital': typeof AuthenticatedCheckInDigitalRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/controle-ponto': typeof AuthenticatedControlePontoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/estoque-geral': typeof AuthenticatedEstoqueGeralRoute
  '/frigobar': typeof AuthenticatedFrigobarRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/gestao-boas-vindas': typeof AuthenticatedGestaoBoasVindasRoute
  '/historico-caixa': typeof AuthenticatedHistoricoCaixaRoute
  '/historico-limpeza': typeof AuthenticatedHistoricoLimpezaRoute
  '/historico-manutencao': typeof AuthenticatedHistoricoManutencaoRoute
  '/historico-vistorias': typeof AuthenticatedHistoricoVistoriasRoute
  '/minha-escala': typeof AuthenticatedMinhaEscalaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/preventiva': typeof AuthenticatedPreventivaRoute
  '/previsao-carga': typeof AuthenticatedPrevisaoCargaRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/relatorio-operacoes': typeof AuthenticatedRelatorioOperacoesRoute
  '/relatorios-turno': typeof AuthenticatedRelatoriosTurnoRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/vistoria': typeof AuthenticatedVistoriaRoute
  '/auth/admin': typeof AuthAdminRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/gestor/escala': typeof AuthenticatedGestorEscalaRoute
  '/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/gestor/ponto': typeof AuthenticatedGestorPontoRoute
  '/gestor/previsao-carga': typeof AuthenticatedGestorPrevisaoCargaRoute
  '/gestor/tarefas-extras': typeof AuthenticatedGestorTarefasExtrasRoute
  '/gestor/totem': typeof AuthenticatedGestorTotemRoute
  '/api/public/bonus-meta': typeof ApiPublicBonusMetaRoute
  '/api/public/cloudbeds-webhook': typeof ApiPublicCloudbedsWebhookRoute
  '/api/public/pagarme-webhook': typeof ApiPublicPagarmeWebhookRoute
  '/api/public/previsao-carga': typeof ApiPublicPrevisaoCargaRoute
  '/api/public/push-dispatcher': typeof ApiPublicPushDispatcherRoute
  '/api/public/tuya-cleanup': typeof ApiPublicTuyaCleanupRoute
  '/gestor': typeof AuthenticatedGestorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/manutencao': typeof ManutencaoRoute
  '/totem': typeof TotemRoute
  '/_authenticated/gestor': typeof AuthenticatedGestorRouteRouteWithChildren
  '/_authenticated/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/_authenticated/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/_authenticated/bonificacao': typeof AuthenticatedBonificacaoRoute
  '/_authenticated/camareiras': typeof AuthenticatedCamareirasRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/check-in-digital': typeof AuthenticatedCheckInDigitalRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/controle-ponto': typeof AuthenticatedControlePontoRoute
  '/_authenticated/escala': typeof AuthenticatedEscalaRoute
  '/_authenticated/estoque-geral': typeof AuthenticatedEstoqueGeralRoute
  '/_authenticated/frigobar': typeof AuthenticatedFrigobarRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/gestao-boas-vindas': typeof AuthenticatedGestaoBoasVindasRoute
  '/_authenticated/historico-caixa': typeof AuthenticatedHistoricoCaixaRoute
  '/_authenticated/historico-limpeza': typeof AuthenticatedHistoricoLimpezaRoute
  '/_authenticated/historico-manutencao': typeof AuthenticatedHistoricoManutencaoRoute
  '/_authenticated/historico-vistorias': typeof AuthenticatedHistoricoVistoriasRoute
  '/_authenticated/minha-escala': typeof AuthenticatedMinhaEscalaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/ponto': typeof AuthenticatedPontoRoute
  '/_authenticated/preventiva': typeof AuthenticatedPreventivaRoute
  '/_authenticated/previsao-carga': typeof AuthenticatedPrevisaoCargaRoute
  '/_authenticated/recepcao': typeof AuthenticatedRecepcaoRoute
  '/_authenticated/relatorio-operacoes': typeof AuthenticatedRelatorioOperacoesRoute
  '/_authenticated/relatorios-turno': typeof AuthenticatedRelatoriosTurnoRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/vistoria': typeof AuthenticatedVistoriaRoute
  '/auth/admin': typeof AuthAdminRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/_authenticated/gestor/escala': typeof AuthenticatedGestorEscalaRoute
  '/_authenticated/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/_authenticated/gestor/ponto': typeof AuthenticatedGestorPontoRoute
  '/_authenticated/gestor/previsao-carga': typeof AuthenticatedGestorPrevisaoCargaRoute
  '/_authenticated/gestor/tarefas-extras': typeof AuthenticatedGestorTarefasExtrasRoute
  '/_authenticated/gestor/totem': typeof AuthenticatedGestorTotemRoute
  '/api/public/bonus-meta': typeof ApiPublicBonusMetaRoute
  '/api/public/cloudbeds-webhook': typeof ApiPublicCloudbedsWebhookRoute
  '/api/public/pagarme-webhook': typeof ApiPublicPagarmeWebhookRoute
  '/api/public/previsao-carga': typeof ApiPublicPrevisaoCargaRoute
  '/api/public/push-dispatcher': typeof ApiPublicPushDispatcherRoute
  '/api/public/tuya-cleanup': typeof ApiPublicTuyaCleanupRoute
  '/_authenticated/gestor/': typeof AuthenticatedGestorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manutencao'
    | '/totem'
    | '/gestor'
    | '/almoxarifado'
    | '/boas-vindas'
    | '/bonificacao'
    | '/camareiras'
    | '/chat'
    | '/check-in-digital'
    | '/configuracoes'
    | '/controle-ponto'
    | '/escala'
    | '/estoque-geral'
    | '/frigobar'
    | '/gestao'
    | '/gestao-boas-vindas'
    | '/historico-caixa'
    | '/historico-limpeza'
    | '/historico-manutencao'
    | '/historico-vistorias'
    | '/minha-escala'
    | '/painel'
    | '/ponto'
    | '/preventiva'
    | '/previsao-carga'
    | '/recepcao'
    | '/relatorio-operacoes'
    | '/relatorios-turno'
    | '/servicos'
    | '/vistoria'
    | '/auth/admin'
    | '/auth/'
    | '/chamados/$id'
    | '/gestor/escala'
    | '/gestor/financeiro'
    | '/gestor/ponto'
    | '/gestor/previsao-carga'
    | '/gestor/tarefas-extras'
    | '/gestor/totem'
    | '/api/public/bonus-meta'
    | '/api/public/cloudbeds-webhook'
    | '/api/public/pagarme-webhook'
    | '/api/public/previsao-carga'
    | '/api/public/push-dispatcher'
    | '/api/public/tuya-cleanup'
    | '/gestor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manutencao'
    | '/totem'
    | '/almoxarifado'
    | '/boas-vindas'
    | '/bonificacao'
    | '/camareiras'
    | '/chat'
    | '/check-in-digital'
    | '/configuracoes'
    | '/controle-ponto'
    | '/escala'
    | '/estoque-geral'
    | '/frigobar'
    | '/gestao'
    | '/gestao-boas-vindas'
    | '/historico-caixa'
    | '/historico-limpeza'
    | '/historico-manutencao'
    | '/historico-vistorias'
    | '/minha-escala'
    | '/painel'
    | '/ponto'
    | '/preventiva'
    | '/previsao-carga'
    | '/recepcao'
    | '/relatorio-operacoes'
    | '/relatorios-turno'
    | '/servicos'
    | '/vistoria'
    | '/auth/admin'
    | '/'
    | '/auth'
    | '/chamados/$id'
    | '/gestor/escala'
    | '/gestor/financeiro'
    | '/gestor/ponto'
    | '/gestor/previsao-carga'
    | '/gestor/tarefas-extras'
    | '/gestor/totem'
    | '/api/public/bonus-meta'
    | '/api/public/cloudbeds-webhook'
    | '/api/public/pagarme-webhook'
    | '/api/public/previsao-carga'
    | '/api/public/push-dispatcher'
    | '/api/public/tuya-cleanup'
    | '/gestor'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/manutencao'
    | '/totem'
    | '/_authenticated/gestor'
    | '/_authenticated/almoxarifado'
    | '/_authenticated/boas-vindas'
    | '/_authenticated/bonificacao'
    | '/_authenticated/camareiras'
    | '/_authenticated/chat'
    | '/_authenticated/check-in-digital'
    | '/_authenticated/configuracoes'
    | '/_authenticated/controle-ponto'
    | '/_authenticated/escala'
    | '/_authenticated/estoque-geral'
    | '/_authenticated/frigobar'
    | '/_authenticated/gestao'
    | '/_authenticated/gestao-boas-vindas'
    | '/_authenticated/historico-caixa'
    | '/_authenticated/historico-limpeza'
    | '/_authenticated/historico-manutencao'
    | '/_authenticated/historico-vistorias'
    | '/_authenticated/minha-escala'
    | '/_authenticated/painel'
    | '/_authenticated/ponto'
    | '/_authenticated/preventiva'
    | '/_authenticated/previsao-carga'
    | '/_authenticated/recepcao'
    | '/_authenticated/relatorio-operacoes'
    | '/_authenticated/relatorios-turno'
    | '/_authenticated/servicos'
    | '/_authenticated/vistoria'
    | '/auth/admin'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/chamados/$id'
    | '/_authenticated/gestor/escala'
    | '/_authenticated/gestor/financeiro'
    | '/_authenticated/gestor/ponto'
    | '/_authenticated/gestor/previsao-carga'
    | '/_authenticated/gestor/tarefas-extras'
    | '/_authenticated/gestor/totem'
    | '/api/public/bonus-meta'
    | '/api/public/cloudbeds-webhook'
    | '/api/public/pagarme-webhook'
    | '/api/public/previsao-carga'
    | '/api/public/push-dispatcher'
    | '/api/public/tuya-cleanup'
    | '/_authenticated/gestor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ManutencaoRoute: typeof ManutencaoRoute
  TotemRoute: typeof TotemRoute
  ApiPublicBonusMetaRoute: typeof ApiPublicBonusMetaRoute
  ApiPublicCloudbedsWebhookRoute: typeof ApiPublicCloudbedsWebhookRoute
  ApiPublicPagarmeWebhookRoute: typeof ApiPublicPagarmeWebhookRoute
  ApiPublicPrevisaoCargaRoute: typeof ApiPublicPrevisaoCargaRoute
  ApiPublicPushDispatcherRoute: typeof ApiPublicPushDispatcherRoute
  ApiPublicTuyaCleanupRoute: typeof ApiPublicTuyaCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/almoxarifado': {
      id: '/_authenticated/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AuthenticatedAlmoxarifadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boas-vindas': {
      id: '/_authenticated/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof AuthenticatedBoasVindasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bonificacao': {
      id: '/_authenticated/bonificacao'
      path: '/bonificacao'
      fullPath: '/bonificacao'
      preLoaderRoute: typeof AuthenticatedBonificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/camareiras': {
      id: '/_authenticated/camareiras'
      path: '/camareiras'
      fullPath: '/camareiras'
      preLoaderRoute: typeof AuthenticatedCamareirasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in-digital': {
      id: '/_authenticated/check-in-digital'
      path: '/check-in-digital'
      fullPath: '/check-in-digital'
      preLoaderRoute: typeof AuthenticatedCheckInDigitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controle-ponto': {
      id: '/_authenticated/controle-ponto'
      path: '/controle-ponto'
      fullPath: '/controle-ponto'
      preLoaderRoute: typeof AuthenticatedControlePontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala': {
      id: '/_authenticated/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof AuthenticatedEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque-geral': {
      id: '/_authenticated/estoque-geral'
      path: '/estoque-geral'
      fullPath: '/estoque-geral'
      preLoaderRoute: typeof AuthenticatedEstoqueGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frigobar': {
      id: '/_authenticated/frigobar'
      path: '/frigobar'
      fullPath: '/frigobar'
      preLoaderRoute: typeof AuthenticatedFrigobarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao-boas-vindas': {
      id: '/_authenticated/gestao-boas-vindas'
      path: '/gestao-boas-vindas'
      fullPath: '/gestao-boas-vindas'
      preLoaderRoute: typeof AuthenticatedGestaoBoasVindasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestor': {
      id: '/_authenticated/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof AuthenticatedGestorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-caixa': {
      id: '/_authenticated/historico-caixa'
      path: '/historico-caixa'
      fullPath: '/historico-caixa'
      preLoaderRoute: typeof AuthenticatedHistoricoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-limpeza': {
      id: '/_authenticated/historico-limpeza'
      path: '/historico-limpeza'
      fullPath: '/historico-limpeza'
      preLoaderRoute: typeof AuthenticatedHistoricoLimpezaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-manutencao': {
      id: '/_authenticated/historico-manutencao'
      path: '/historico-manutencao'
      fullPath: '/historico-manutencao'
      preLoaderRoute: typeof AuthenticatedHistoricoManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-vistorias': {
      id: '/_authenticated/historico-vistorias'
      path: '/historico-vistorias'
      fullPath: '/historico-vistorias'
      preLoaderRoute: typeof AuthenticatedHistoricoVistoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-escala': {
      id: '/_authenticated/minha-escala'
      path: '/minha-escala'
      fullPath: '/minha-escala'
      preLoaderRoute: typeof AuthenticatedMinhaEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ponto': {
      id: '/_authenticated/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof AuthenticatedPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preventiva': {
      id: '/_authenticated/preventiva'
      path: '/preventiva'
      fullPath: '/preventiva'
      preLoaderRoute: typeof AuthenticatedPreventivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/previsao-carga': {
      id: '/_authenticated/previsao-carga'
      path: '/previsao-carga'
      fullPath: '/previsao-carga'
      preLoaderRoute: typeof AuthenticatedPrevisaoCargaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepcao': {
      id: '/_authenticated/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof AuthenticatedRecepcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio-operacoes': {
      id: '/_authenticated/relatorio-operacoes'
      path: '/relatorio-operacoes'
      fullPath: '/relatorio-operacoes'
      preLoaderRoute: typeof AuthenticatedRelatorioOperacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios-turno': {
      id: '/_authenticated/relatorios-turno'
      path: '/relatorios-turno'
      fullPath: '/relatorios-turno'
      preLoaderRoute: typeof AuthenticatedRelatoriosTurnoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vistoria': {
      id: '/_authenticated/vistoria'
      path: '/vistoria'
      fullPath: '/vistoria'
      preLoaderRoute: typeof AuthenticatedVistoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/chamados/$id': {
      id: '/_authenticated/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof AuthenticatedChamadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestor/': {
      id: '/_authenticated/gestor/'
      path: '/'
      fullPath: '/gestor/'
      preLoaderRoute: typeof AuthenticatedGestorIndexRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/escala': {
      id: '/_authenticated/gestor/escala'
      path: '/escala'
      fullPath: '/gestor/escala'
      preLoaderRoute: typeof AuthenticatedGestorEscalaRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/financeiro': {
      id: '/_authenticated/gestor/financeiro'
      path: '/financeiro'
      fullPath: '/gestor/financeiro'
      preLoaderRoute: typeof AuthenticatedGestorFinanceiroRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/ponto': {
      id: '/_authenticated/gestor/ponto'
      path: '/ponto'
      fullPath: '/gestor/ponto'
      preLoaderRoute: typeof AuthenticatedGestorPontoRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/previsao-carga': {
      id: '/_authenticated/gestor/previsao-carga'
      path: '/previsao-carga'
      fullPath: '/gestor/previsao-carga'
      preLoaderRoute: typeof AuthenticatedGestorPrevisaoCargaRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/tarefas-extras': {
      id: '/_authenticated/gestor/tarefas-extras'
      path: '/tarefas-extras'
      fullPath: '/gestor/tarefas-extras'
      preLoaderRoute: typeof AuthenticatedGestorTarefasExtrasRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/totem': {
      id: '/_authenticated/gestor/totem'
      path: '/totem'
      fullPath: '/gestor/totem'
      preLoaderRoute: typeof AuthenticatedGestorTotemRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/api/public/bonus-meta': {
      id: '/api/public/bonus-meta'
      path: '/api/public/bonus-meta'
      fullPath: '/api/public/bonus-meta'
      preLoaderRoute: typeof ApiPublicBonusMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudbeds-webhook': {
      id: '/api/public/cloudbeds-webhook'
      path: '/api/public/cloudbeds-webhook'
      fullPath: '/api/public/cloudbeds-webhook'
      preLoaderRoute: typeof ApiPublicCloudbedsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pagarme-webhook': {
      id: '/api/public/pagarme-webhook'
      path: '/api/public/pagarme-webhook'
      fullPath: '/api/public/pagarme-webhook'
      preLoaderRoute: typeof ApiPublicPagarmeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/previsao-carga': {
      id: '/api/public/previsao-carga'
      path: '/api/public/previsao-carga'
      fullPath: '/api/public/previsao-carga'
      preLoaderRoute: typeof ApiPublicPrevisaoCargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatcher': {
      id: '/api/public/push-dispatcher'
      path: '/api/public/push-dispatcher'
      fullPath: '/api/public/push-dispatcher'
      preLoaderRoute: typeof ApiPublicPushDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tuya-cleanup': {
      id: '/api/public/tuya-cleanup'
      path: '/api/public/tuya-cleanup'
      fullPath: '/api/public/tuya-cleanup'
      preLoaderRoute: typeof ApiPublicTuyaCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedGestorRouteRouteChildren {
  AuthenticatedGestorEscalaRoute: typeof AuthenticatedGestorEscalaRoute
  AuthenticatedGestorFinanceiroRoute: typeof AuthenticatedGestorFinanceiroRoute
  AuthenticatedGestorPontoRoute: typeof AuthenticatedGestorPontoRoute
  AuthenticatedGestorPrevisaoCargaRoute: typeof AuthenticatedGestorPrevisaoCargaRoute
  AuthenticatedGestorTarefasExtrasRoute: typeof AuthenticatedGestorTarefasExtrasRoute
  AuthenticatedGestorTotemRoute: typeof AuthenticatedGestorTotemRoute
  AuthenticatedGestorIndexRoute: typeof AuthenticatedGestorIndexRoute
}

const AuthenticatedGestorRouteRouteChildren: AuthenticatedGestorRouteRouteChildren =
  {
    AuthenticatedGestorEscalaRoute: AuthenticatedGestorEscalaRoute,
    AuthenticatedGestorFinanceiroRoute: AuthenticatedGestorFinanceiroRoute,
    AuthenticatedGestorPontoRoute: AuthenticatedGestorPontoRoute,
    AuthenticatedGestorPrevisaoCargaRoute:
      AuthenticatedGestorPrevisaoCargaRoute,
    AuthenticatedGestorTarefasExtrasRoute:
      AuthenticatedGestorTarefasExtrasRoute,
    AuthenticatedGestorTotemRoute: AuthenticatedGestorTotemRoute,
    AuthenticatedGestorIndexRoute: AuthenticatedGestorIndexRoute,
  }

const AuthenticatedGestorRouteRouteWithChildren =
  AuthenticatedGestorRouteRoute._addFileChildren(
    AuthenticatedGestorRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGestorRouteRoute: typeof AuthenticatedGestorRouteRouteWithChildren
  AuthenticatedAlmoxarifadoRoute: typeof AuthenticatedAlmoxarifadoRoute
  AuthenticatedBoasVindasRoute: typeof AuthenticatedBoasVindasRoute
  AuthenticatedBonificacaoRoute: typeof AuthenticatedBonificacaoRoute
  AuthenticatedCamareirasRoute: typeof AuthenticatedCamareirasRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCheckInDigitalRoute: typeof AuthenticatedCheckInDigitalRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedControlePontoRoute: typeof AuthenticatedControlePontoRoute
  AuthenticatedEscalaRoute: typeof AuthenticatedEscalaRoute
  AuthenticatedEstoqueGeralRoute: typeof AuthenticatedEstoqueGeralRoute
  AuthenticatedFrigobarRoute: typeof AuthenticatedFrigobarRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedGestaoBoasVindasRoute: typeof AuthenticatedGestaoBoasVindasRoute
  AuthenticatedHistoricoCaixaRoute: typeof AuthenticatedHistoricoCaixaRoute
  AuthenticatedHistoricoLimpezaRoute: typeof AuthenticatedHistoricoLimpezaRoute
  AuthenticatedHistoricoManutencaoRoute: typeof AuthenticatedHistoricoManutencaoRoute
  AuthenticatedHistoricoVistoriasRoute: typeof AuthenticatedHistoricoVistoriasRoute
  AuthenticatedMinhaEscalaRoute: typeof AuthenticatedMinhaEscalaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPontoRoute: typeof AuthenticatedPontoRoute
  AuthenticatedPreventivaRoute: typeof AuthenticatedPreventivaRoute
  AuthenticatedPrevisaoCargaRoute: typeof AuthenticatedPrevisaoCargaRoute
  AuthenticatedRecepcaoRoute: typeof AuthenticatedRecepcaoRoute
  AuthenticatedRelatorioOperacoesRoute: typeof AuthenticatedRelatorioOperacoesRoute
  AuthenticatedRelatoriosTurnoRoute: typeof AuthenticatedRelatoriosTurnoRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedVistoriaRoute: typeof AuthenticatedVistoriaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChamadosIdRoute: typeof AuthenticatedChamadosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGestorRouteRoute: AuthenticatedGestorRouteRouteWithChildren,
  AuthenticatedAlmoxarifadoRoute: AuthenticatedAlmoxarifadoRoute,
  AuthenticatedBoasVindasRoute: AuthenticatedBoasVindasRoute,
  AuthenticatedBonificacaoRoute: AuthenticatedBonificacaoRoute,
  AuthenticatedCamareirasRoute: AuthenticatedCamareirasRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCheckInDigitalRoute: AuthenticatedCheckInDigitalRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedControlePontoRoute: AuthenticatedControlePontoRoute,
  AuthenticatedEscalaRoute: AuthenticatedEscalaRoute,
  AuthenticatedEstoqueGeralRoute: AuthenticatedEstoqueGeralRoute,
  AuthenticatedFrigobarRoute: AuthenticatedFrigobarRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedGestaoBoasVindasRoute: AuthenticatedGestaoBoasVindasRoute,
  AuthenticatedHistoricoCaixaRoute: AuthenticatedHistoricoCaixaRoute,
  AuthenticatedHistoricoLimpezaRoute: AuthenticatedHistoricoLimpezaRoute,
  AuthenticatedHistoricoManutencaoRoute: AuthenticatedHistoricoManutencaoRoute,
  AuthenticatedHistoricoVistoriasRoute: AuthenticatedHistoricoVistoriasRoute,
  AuthenticatedMinhaEscalaRoute: AuthenticatedMinhaEscalaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPontoRoute: AuthenticatedPontoRoute,
  AuthenticatedPreventivaRoute: AuthenticatedPreventivaRoute,
  AuthenticatedPrevisaoCargaRoute: AuthenticatedPrevisaoCargaRoute,
  AuthenticatedRecepcaoRoute: AuthenticatedRecepcaoRoute,
  AuthenticatedRelatorioOperacoesRoute: AuthenticatedRelatorioOperacoesRoute,
  AuthenticatedRelatoriosTurnoRoute: AuthenticatedRelatoriosTurnoRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedVistoriaRoute: AuthenticatedVistoriaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChamadosIdRoute: AuthenticatedChamadosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ManutencaoRoute: ManutencaoRoute,
  TotemRoute: TotemRoute,
  ApiPublicBonusMetaRoute: ApiPublicBonusMetaRoute,
  ApiPublicCloudbedsWebhookRoute: ApiPublicCloudbedsWebhookRoute,
  ApiPublicPagarmeWebhookRoute: ApiPublicPagarmeWebhookRoute,
  ApiPublicPrevisaoCargaRoute: ApiPublicPrevisaoCargaRoute,
  ApiPublicPushDispatcherRoute: ApiPublicPushDispatcherRoute,
  ApiPublicTuyaCleanupRoute: ApiPublicTuyaCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
